controller:
  diff_drive_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: ['car_base_front_left_wheel','car_base_back_left_wheel']
    right_wheel: ['car_base_front_right_wheel','car_base_back_right_wheel']
    pose_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
    twist_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
gazebo_ros_control:
  pid_gains:
    car_base_back_left_wheel:
        p: 1.0
        i: 0.0
        d: 0.0
    car_base_back_right_wheel:
        p: 1.0
        i: 0.0
        d: 0.0
    car_base_front_left_wheel:
        p: 1.0
        i: 0.0
        d: 0.0
    car_base_front_right_wheel:
        p: 1.0
        i: 0.0
        d: 0.0