<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pole_machine">
  <xacro:property name="pole_radius" value="0.2"/>
  <xacro:property name="pole_length" value="5"/>
  <xacro:property name="mass" value="50.0"/>
  <xacro:property name="PI" value="3.14159265358979323846"/>

  <link name="base_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </link>

  <link name="pole_link">
    <visual>
      <geometry>
        <cylinder length="${pole_length}" radius="${pole_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
      <origin xyz="0 0 ${pole_length/2}" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${pole_length}" radius="${pole_radius}"/>
      </geometry>
      <origin xyz="0 0 ${pole_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="10000"/>
      <origin xyz="0 0 ${pole_length/2}" rpy="0 0 0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
  </link>

  <link name="motor_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="0.1" length="0.5"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
      <geometry>
        <cylinder radius="0.1" length="0.5"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <link name="bar_link">
    <visual>
      <origin xyz="0.2 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="4.0" radius="0.05"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.2 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="4.0" radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0.2 0 0" rpy="0 0 0"/>
      <!-- 计算转动惯量，利用公式I=1/12​ML^2 -->
      <inertia ixx="105" ixy="0" ixz="0" iyy="105" iyz="0" izz="100"/>
    </inertial>
  </link>

  <joint name="pole_joint" type="fixed">
    <parent link="base_link"/>
    <child link="pole_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="motor_joint" type="fixed">
    <parent link="pole_link"/>
    <child link="motor_link"/>
    <origin xyz="0.2 0 ${pole_length - 0.25}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <joint name="bar_joint" type="continuous">
    <parent link="motor_link"/>
    <child link="bar_link"/>
    <origin xyz="0.0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <transmission name="motor_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="bar_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="bar_motor">
      <mechanicalReduction>1</mechanicalReduction>      <!--传动比定为1-->
    </actuator>
  </transmission>


  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>
</robot>
