controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  power_machine_controller:
    type: power_machine_controller/PowerMachineController
    publish_rate: 50
    pid:
      p: 100   # 位置比例增益
      i: 1    # 积分增益，设置较小以避免积分饱和
      d: 0     # 微分增益，用于抑制超调
    feedforward:
      k: 5000
    joints:
      - bar_joint   # 控制的关节名称
    constraints:
      effort_limit: 100.0   # 力矩限制
      velocity_limit: 10.0  # 速度限制（rad/s）  （用不上）
